import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    governmentSchemes: 'Government Schemes',
    voiceChat: 'Voice Chat',
    profile: 'Profile',
    aboutUs: 'About Us',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    help: 'Help',
    startVoiceChat: 'Start Voice Chat',
    viewSchemes: 'View Schemes',
    yourHealthAssistant: 'Your Health Assistant',
    withAI: 'with AI',
    getHealthAdvice: 'Get health advice in your language. Speak or type your symptoms.',
    voiceChatFeature: 'Voice Chat',
    voiceChatDesc: 'Speak your symptoms in your language',
    schemesFeature: 'Government Schemes',
    schemesDesc: 'Get information about all health schemes',
    personalFeature: 'Personal Assistance',
    personalDesc: 'Create your profile and get personalized help',
    copyright: '© 2024 Health Assistant. All rights reserved.',
    tollFree: 'Toll Free',
    email: 'Email',
    address: 'Address',
    newDelhi: 'New Delhi, India',
    selectLanguage: 'Select Language',
    personalAssistant: {
      title: 'Personal Assistant',
      placeholder: 'Type your message here...',
      listening: 'Listening...',
      stopListening: 'Stop Listening',
      startListening: 'Start Voice Input',
      send: 'Send Message',
      processing: 'Processing...'
    }
  },
  hi: {
    home: 'मुख्य पृष्ठ',
    governmentSchemes: 'सरकारी योजनाएं',
    voiceChat: 'आवाज़ चैट',
    profile: 'प्रोफ़ाइल',
    aboutUs: 'हमारे बारे में',
    quickLinks: 'त्वरित लिंक',
    contactUs: 'संपर्क करें',
    privacyPolicy: 'निजता नीति',
    termsOfUse: 'उपयोग की शर्तें',
    help: 'सहायता',
    startVoiceChat: 'आवाज़ से बात करें',
    viewSchemes: 'सरकारी योजनाएं देखें',
    yourHealthAssistant: 'आपका स्वास्थ्य सहायक',
    withAI: 'AI के साथ',
    getHealthAdvice: 'अपनी भाषा में स्वास्थ्य सलाह प्राप्त करें। बोलकर या लिखकर अपनी समस्या बताएं।',
    voiceChatFeature: 'आवाज़ से बात करें',
    voiceChatDesc: 'अपनी भाषा में बोलकर अपनी समस्या बताएं',
    schemesFeature: 'सरकारी योजनाएं',
    schemesDesc: 'सभी स्वास्थ्य योजनाओं की जानकारी प्राप्त करें',
    personalFeature: 'व्यक्तिगत सहायता',
    personalDesc: 'अपनी प्रोफ़ाइल बनाएं और व्यक्तिगत सहायता प्राप्त करें',
    copyright: '© 2024 स्वास्थ्य सहायक। सर्वाधिकार सुरक्षित।',
    tollFree: 'टोल फ्री',
    email: 'ईमेल',
    address: 'पता',
    newDelhi: 'नई दिल्ली, भारत',
    selectLanguage: 'भाषा चुनें',
    personalAssistant: {
      title: 'व्यक्तिगत सहायक',
      placeholder: 'यहां अपना संदेश टाइप करें...',
      listening: 'सुन रहा है...',
      stopListening: 'सुनना बंद करें',
      startListening: 'आवाज़ इनपुट शुरू करें',
      send: 'संदेश भेजें',
      processing: 'प्रोसेसिंग...'
    }
  },
  bn: {
    home: 'হোম',
    governmentSchemes: 'সরকারি প্রকল্প',
    voiceChat: 'ভয়েস চ্যাট',
    profile: 'প্রোফাইল',
    aboutUs: 'আমাদের সম্পর্কে',
    quickLinks: 'সহজ লিঙ্ক',
    contactUs: 'যোগাযোগ করুন',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfUse: 'ব্যবহারের শর্তাবলী',
    help: 'সাহায্য',
    startVoiceChat: 'ভয়েস চ্যাট শুরু করুন',
    viewSchemes: 'প্রকল্পগুলি দেখুন',
    yourHealthAssistant: 'আপনার স্বাস্থ্য সহকারী',
    withAI: 'এআই সহ',
    getHealthAdvice: 'আপনার ভাষায় স্বাস্থ্য পরামর্শ পান। আপনার লক্ষণগুলি বলুন বা টাইপ করুন।',
    voiceChatFeature: 'ভয়েস চ্যাট',
    voiceChatDesc: 'আপনার ভাষায় আপনার লক্ষণগুলি বলুন',
    schemesFeature: 'সরকারি প্রকল্প',
    schemesDesc: 'সমস্ত স্বাস্থ্য প্রকল্প সম্পর্কে তথ্য পান',
    personalFeature: 'ব্যক্তিগত সহায়তা',
    personalDesc: 'আপনার প্রোফাইল তৈরি করুন এবং ব্যক্তিগত সহায়তা পান',
    copyright: '© 2024 স্বাস্থ্য সহকারী। সমস্ত অধিকার সংরক্ষিত।',
    tollFree: 'টোল ফ্রি',
    email: 'ইমেল',
    address: 'ঠিকানা',
    newDelhi: 'নয়াদিল্লি, ভারত',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    personalAssistant: {
      title: 'ব্যক্তিগত সহকারী',
      placeholder: 'এখানে আপনার বার্তা টাইপ করুন...',
      listening: 'শুনছি...',
      stopListening: 'শোনা বন্ধ করুন',
      startListening: 'ভয়েস ইনপুট শুরু করুন',
      send: 'বার্তা পাঠান',
      processing: 'প্রসেসিং...'
    }
  },
  ta: {
    home: 'முகப்பு',
    governmentSchemes: 'அரசு திட்டங்கள்',
    voiceChat: 'குரல் அரட்டை',
    profile: 'சுயவிவரம்',
    aboutUs: 'எங்களை பற்றி',
    quickLinks: 'விரைவு இணைப்புகள்',
    contactUs: 'தொடர்பு கொள்ளுங்கள்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfUse: 'பயன்பாட்டு விதிமுறைகள்',
    help: 'உதவி',
    startVoiceChat: 'குரல் அரட்டையைத் தொடங்கு',
    viewSchemes: 'திட்டங்களைப் பார்',
    yourHealthAssistant: 'உங்கள் சுகாதார உதவியாளர்',
    withAI: 'AI உடன்',
    getHealthAdvice: 'உங்கள் மொழியில் சுகாதார ஆலோசனை பெறுங்கள். உங்கள் அறிகுறிகளைப் பேசுங்கள் அல்லது தட்டச்சு செய்யவும்.',
    voiceChatFeature: 'குரல் அரட்டை',
    voiceChatDesc: 'உங்கள் மொழியில் உங்கள் அறிகுறிகளைப் பேசுங்கள்',
    schemesFeature: 'அரசு திட்டங்கள்',
    schemesDesc: 'அனைத்து சுகாதார திட்டங்கள் பற்றிய தகவல்களைப் பெறுங்கள்',
    personalFeature: 'தனிப்பட்ட உதவி',
    personalDesc: 'உங்கள் சுயவிவரத்தை உருவாக்கி தனிப்பயனாக்கப்பட்ட உதவியைப் பெறுங்கள்',
    copyright: '© 2024 சுகாதார உதவியாளர். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    tollFree: 'கட்டணமில்லா',
    email: 'மின்னஞ்சல்',
    address: 'முகவரி',
    newDelhi: 'புது டெல்லி, இந்தியா',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுங்கள்',
    personalAssistant: {
      title: 'தனிப்பட்ட உதவியாளர்',
      placeholder: 'உங்கள் செய்தியை இங்கு தட்டச்சு செய்யவும்...',
      listening: 'கேட்டுக்கொண்டிருக்கிறது...',
      stopListening: 'கேட்பதை நிறுத்து',
      startListening: 'குரல் உள்ளீட்டைத் தொடங்கு',
      send: 'செய்தி அனுப்பு',
      processing: 'செயல்முறைப்படுத்தப்படுகிறது...'
    }
  },
  te: {
    home: 'హోమ్',
    governmentSchemes: 'ప్రభుత్వ పథకాలు',
    voiceChat: 'వాయిస్ చాట్',
    profile: 'ప్రొఫైల్',
    aboutUs: 'మా గురించి',
    quickLinks: 'త్వరిత లింకులు',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfUse: 'వినియోగ నిబంధనలు',
    help: 'సహాయం',
    startVoiceChat: 'వాయిస్ చాట్ ప్రారంభించండి',
    viewSchemes: 'పథకాలను వీక్షించండి',
    yourHealthAssistant: 'మీ ఆరోగ్య సహాయకుడు',
    withAI: 'AIతో',
    getHealthAdvice: 'మీ భాషోలో ఆరోగ్య సలహೆ పొందండి. మీ లక్షణాలను మాట్లాడండి లేదా టైప్ చేయండి.',
    voiceChatFeature: 'వాయిస్ చాట్',
    voiceChatDesc: 'మీ భాషోలో మీ లక్షణాలను మాట్లాడండి',
    schemesFeature: 'ప్రభుత్వ పథకాలు',
    schemesDesc: 'అన్ని ఆరోగ్య పథకాల గురించి సమాచారం పొందండి',
    personalFeature: 'వ్యక్తిగత సహాయం',
    personalDesc: 'మీ ప్రొఫైల్‌ను సృష్టించండి మత್తು వ్యక్తిగత సహాయ పొందండి',
    copyright: '© 2024 ఆరోగ్య సహాయకుడు. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    tollFree: 'టోల్ ఫ్రీ',
    email: 'ఇమెయిల్',
    address: 'చిరునామా',
    newDelhi: 'న్యూఢిల్లీ, భారతదేశం',
    selectLanguage: 'భాషను ఎంచుకోండి',
    personalAssistant: {
      title: 'వ్యక్తిగత సహాయకుడు',
      placeholder: 'మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి...',
      listening: 'వింటుంది...',
      stopListening: 'వినియోగించవద్దు',
      startListening: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
      send: 'సందేశం పంపండి',
      processing: 'ప్రాసెసింగ్...'
    }
  },
  mr: {
    home: 'मुख्यपृष्ठ',
    governmentSchemes: 'सरकारी योजना',
    voiceChat: 'व्हॉइस चॅट',
    profile: 'प्रोफाइल',
    aboutUs: 'आमच्याबद्दल',
    quickLinks: 'त्वरित लिंक्स',
    contactUs: 'संपर्क साधा',
    privacyPolicy: 'गोपनीयता धोरण',
    termsOfUse: 'वापराच्या अटी',
    help: 'मदत',
    startVoiceChat: 'व्हॉइस चॅट सुरू करा',
    viewSchemes: 'योजना पहा',
    yourHealthAssistant: 'तुमचा आरोग्य सहायक',
    withAI: 'AI सह',
    getHealthAdvice: 'आपल्या भाषेत आरोग्य सल्ला मिळवा. आपली लक्षणे बोला किंवा टाइप करा.',
    voiceChatFeature: 'व्हॉइस चॅट',
    voiceChatDesc: 'आपल्या भाषेत आपली लक्षणे बोला',
    schemesFeature: 'सरकारी योजना',
    schemesDesc: 'सर्व आरोग्य योजनांबद्दल माहिती मिळवा',
    personalFeature: 'वैयक्तिक सहाय्य',
    personalDesc: 'आपले प्रोफाइल तयार करा आणि वैयक्तिक मदत मिळवा',
    copyright: '© 2024 आरोग्य सहायक. सर्व हक्क राखीव.',
    tollFree: 'टोल फ्री',
    email: 'ईमेल',
    address: 'पत्ता',
    newDelhi: 'नवी दिल्ली, भारत',
    selectLanguage: 'भाषा निवडा',
    personalAssistant: {
      title: 'वैयक्तिक सहायक',
      placeholder: 'येथे आपला संदेश टाइप करा...',
      listening: 'ऐकत आहे...',
      stopListening: 'ऐकणे थांबवा',
      startListening: 'व्हॉइस इनपुट सुरू करा',
      send: 'संदेश पाठवा',
      processing: 'प्रक्रिया करत आहे...'
    }
  },
  gu: {
    home: 'હોમ',
    governmentSchemes: 'સરકારી યોજનાઓ',
    voiceChat: 'વોઇસ ચેટ',
    profile: 'પ્રોફાઇલ',
    aboutUs: 'અમારા વિશે',
    quickLinks: 'ઝડપી લિંક્સ',
    contactUs: 'અમારો સંપર્ક કરો',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    termsOfUse: 'ઉપયોગની શર્તો',
    help: 'મદદ',
    startVoiceChat: 'વોઇસ ચેટ શરૂ કરો',
    viewSchemes: 'યોજનાઓ જુઓ',
    yourHealthAssistant: 'તમારો સ્વાસ્થ્ય સહાયક',
    withAI: 'AI સાથે',
    getHealthAdvice: 'તમારી ભાષામાં આરોગ્ય સલાહ મેળવો. તમારા લક્ષણો બોલો અથવા ટાઇપ કરો.',
    voiceChatFeature: 'વોઇસ ચેટ',
    voiceChatDesc: 'તમારી ભાષામાં તમારા લક્ષણો બોલો',
    schemesFeature: 'સરકારી યોજનાઓ',
    schemesDesc: 'બધી આરોગ્ય યોજનાઓ વિશે માહિતી મેળવો',
    personalFeature: 'વ્યક્તિગત સહાય',
    personalDesc: 'તમારી પ્રોફાઇલ બનાવો અને વ્યક્તિગત સહાય મેળવો',
    copyright: '© 2024 સ્વાસ્થ્ય સહાયક. સર્વાધિકાર સુરક્ષિત.',
    tollFree: 'ટોલ ફ્રી',
    email: 'ઇમેઇલ',
    address: 'સરનામું',
    newDelhi: 'નવી દિલ્હી, ભારત',
    selectLanguage: 'ભાષા પસંદ કરો',
    personalAssistant: {
      title: 'વ્યક્તિગત સહાયક',
      placeholder: 'અહીં તમારો સંદેશ ટાઇપ કરો...',
      listening: 'સાંભળી રહ્યું છે...',
      stopListening: 'સાંભળવાનું બંધ કરો',
      startListening: 'વોઇસ ઇનપુટ શરૂ કરો',
      send: 'સંદેશ મોકલો',
      processing: 'પ્રક્રિયા કરી રહ્યું છે...'
    }
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    governmentSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    voiceChat: 'ಧ್ವನಿ ಚಾಟ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    termsOfUse: 'ಬಳಕೆಯ ನಿಯಮಗಳು',
    help: 'ಸಹಾಯ',
    startVoiceChat: 'ಧ್ವನಿ ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    viewSchemes: 'ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    yourHealthAssistant: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಸಹಾಯಕ',
    withAI: 'AI ಜೊತೆ',
    getHealthAdvice: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಆರೋಗ್ಯ ಸಲಹೆ ಪಡೆಯಿರಿ. ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಮಾತನಾಡಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.',
    voiceChatFeature: 'ಧ್ವನಿ ಚಾಟ್',
    voiceChatDesc: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ಮಾತನಾಡಿ',
    schemesFeature: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    schemesDesc: 'ಎಲ್ಲಾ ಆರೋಗ್ಯ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಮಾಹಿತಿ ಪಡೆಯಿರಿ',
    personalFeature: 'ವೈಯಕ್ತಿಕ ಸಹಾಯ',
    personalDesc: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಸಹಾಯ ಪಡೆಯಿರಿ',
    copyright: '© 2024 ಆರೋಗ್ಯ ಸಹಾಯಕ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    tollFree: 'ಟೋಲ್ ಫ್ರೀ',
    email: 'ಇಮೇಲ್',
    address: 'ವಿಳಾಸ',
    newDelhi: 'ನವದೆಹಲಿ, ಭಾರತ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    personalAssistant: {
      title: 'ವೈಯಕ್ತಿಕ ಸಹಾಯಕ',
      placeholder: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
      listening: 'ಕೇಳುತ್ತಿದೆ...',
      stopListening: 'ಕೇಳುವುದನ್ನು ನಿಲ್ಲಿಸಿ',
      startListening: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಪ್ರಾರಂಭಿಸಿ',
      send: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      processing: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...'
    }
  },
  ml: {
    home: 'ഹോം',
    governmentSchemes: 'സർക്കാർ പദ്ധതികൾ',
    voiceChat: 'വോയിസ് ചാറ്റ്',
    profile: 'പ്രൊഫൈൽ',
    aboutUs: 'ഞങ്ങളെക്കുറിച്ച്',
    quickLinks: 'ദ്രുത ലിങ്കുകൾ',
    contactUs: 'ഞങ്ങളെ സമീപിക്കുക',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    termsOfUse: 'ഉപയോഗ നിബന്ധനകൾ',
    help: 'സഹായം',
    startVoiceChat: 'വോയിസ് ചാറ്റ് ആരംഭിക്കുക',
    viewSchemes: 'പദ്ധതികൾ കാണുക',
    yourHealthAssistant: 'നിങ്ങളുടെ ആരോഗ്യ സഹായി',
    withAI: 'AI ഉപയോഗിച്ച്',
    getHealthAdvice: 'നിങ്ങളുടെ ഭാഷയിൽ ആരോഗ്യ ഉപദേശം നേടുക. നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ സംസാരിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക.',
    voiceChatFeature: 'വോയിസ് ചാറ്റ്',
    voiceChatDesc: 'നിങ്ങളുടെ ഭാഷയിൽ നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ സംസാരിക്കുക',
    schemesFeature: 'സർക്കാർ പദ്ധതികൾ',
    schemesDesc: 'എല്ലാ ആരോഗ്യ പദ്ധതികളെക്കുറിച്ചും വിവരങ്ങൾ നേടുക',
    personalFeature: 'വ്യക്തിഗത സഹായം',
    personalDesc: 'നിങ്ങളുടെ പ്രൊഫൈൽ സൃഷ്ടിച്ച് വ്യക്തിഗത സഹായം നേടുക',
    copyright: '© 2024 ആരോഗ്യ സഹായി. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',
    tollFree: 'ടോൾ ഫ്രീ',
    email: 'ഇമെയിൽ',
    address: 'വിലാസം',
    newDelhi: 'ന്യൂഡൽഹി, ഇന്ത്യ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    personalAssistant: {
      title: 'വ്യക്തിഗത സഹായി',
      placeholder: 'നിങ്ങളുടെ സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
      listening: 'ശ്രദ്ധിക്കുന്നു...',
      stopListening: 'ശ്രദ്ധിക്കുന്നത് നിർത്തുക',
      startListening: 'വോയിസ് ഇൻപുട്ട് ആരംഭിക്കുക',
      send: 'സന്ദേശം അയയ്ക്കുക',
      processing: 'പ്രോസസ്സ് ചെയ്യുന്നു...'
    }
  },
  pa: {
    home: 'ਹੋਮ',
    governmentSchemes: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    voiceChat: 'ਵੌਇਸ ਚੈਟ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    aboutUs: 'ਸਾਡੇ ਬਾਰੇ',
    quickLinks: 'ਤੇਜ਼ ਲਿੰਕ',
    contactUs: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    privacyPolicy: 'ਗੋਪનੀਯਤਾ ਨੀਤੀ',
    termsOfUse: 'ਵਰਤੋਂ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    help: 'ਮਦਦ',
    startVoiceChat: 'ਵੌਇਸ ਚੈਟ ਸ਼ੁਰੂ ਕਰੋ',
    viewSchemes: 'ਸਕੀਮਾਂ ਵੇਖੋ',
    yourHealthAssistant: 'ਤੁਹਾਡਾ ਸਿਹਤ ਸਹਾਇਕ',
    withAI: 'AI ਦੇ ਨਾਲ',
    getHealthAdvice: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਿਹਤ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ। ਆਪਣੇ ਲੱਛਣ ਬੋਲੋ ਜਾਂ ਟਾਈਪ ਕਰੋ।',
    voiceChatFeature: 'ਵੌਇਸ ਚੈਟ',
    voiceChatDesc: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣੇ ਲੱਛਣ ਬੋਲੋ',
    schemesFeature: 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    schemesDesc: 'ਸਾਰੀਆਂ ਸਿਹਤ ਸਕੀਮਾਂ ਬਾਰੇ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ',
    personalFeature: 'ਨਿੱਜੀ ਸਹਾਇਤਾ',
    personalDesc: 'ਆਪਣਾ ਪ੍ਰੋਫਾਈਲ ਬનਾਓ ਅਤੇ ਨਿੱਜੀ ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਕਰੋ',
    copyright: '© 2024 ਸਿਹਤ ਸਹਾਇਕ। ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ ਹਨ।',
    tollFree: 'ਟੋਲ ਫ੍ਰੀ',
    email: 'ਈਮੇਲ',
    address: 'ਪਤਾ',
    newDelhi: 'ਨਵੀਂ ਦਿੱਲੀ, ਭਾਰਤ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    personalAssistant: {
      title: 'ਨਿੱਜੀ ਸਹਾਇਕ',
      placeholder: 'ਇੱਥੇ ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      listening: 'ਸੁਣ ਰਿਹਾ ਹੈ...',
      stopListening: 'ਸੁਣਨਾ ਬੰਦ ਕਰੋ',
      startListening: 'ਵੌਇਸ ਇਨਪੁਟ ਸ਼ੁਰੂ ਕਰੋ',
      send: 'ਸੁਨੇਹਾ ਭੇਜੋ',
      processing: 'ਪ੍ਰੋਸੈਸਿੰਗ...'
    }
  },
  ur: {
    home: 'ہوم',
    governmentSchemes: 'حکومتی اسکیمیں',
    voiceChat: 'وائس چیٹ',
    profile: 'پروفائل',
    aboutUs: 'ہمارے بارے میں',
    quickLinks: 'فوری لنکس',
    contactUs: 'ہم سے رابطہ کریں',
    privacyPolicy: 'رازداری کی پالیسی',
    termsOfUse: 'استعمال کی شرائط',
    help: 'مدد',
    startVoiceChat: 'وائس چیٹ شروع کریں',
    viewSchemes: 'اسکیمیں دیکھیں',
    yourHealthAssistant: 'آپ کا ہیلتھ اسسٹنٹ',
    withAI: 'AI کے ساتھ',
    getHealthAdvice: 'اپنی زبان میں صحت کا مشورہ حاصل کریں۔ اپنی علامات بولیں یا ٹائپ کریں۔',
    voiceChatFeature: 'وائس چیٹ',
    voiceChatDesc: 'اپنی زبان میں اپنی علامات بولیں',
    schemesFeature: 'حکومتی اسکیمیں',
    schemesDesc: 'تمام صحت اسکیموں کے بارے میں معلومات حاصل کریں',
    personalFeature: 'ذاتی مدد',
    personalDesc: 'اپنی پروفائل بنائیں اور ذاتی مدد حاصل کریں',
    copyright: '© 2024 ہیلتھ اسسٹنٹ۔ تمام حقوق محفوظ ہیں۔',
    tollFree: 'ٹول فری',
    email: 'ای میل',
    address: 'پتہ',
    newDelhi: 'نئی دہلی، بھارت',
    selectLanguage: 'زبان منتخب کریں',
    personalAssistant: {
      title: 'ذاتی معاون',
      placeholder: 'یہاں اپنا پیغام ٹائپ کریں...',
      listening: 'سن رہا ہے...',
      stopListening: 'سننا بند کریں',
      startListening: 'وائس ان پٹ شروع کریں',
      send: 'پیغام بھیجیں',
      processing: 'پروسیسنگ...'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 